version: '3'

services:
  ubuntu:
    container_name: resspect
    image: ubuntu
    tty: true
    network_mode: host
    command: ["sh", "-c", "echo 'Starting container...';echo 'Updating package lists...';apt update;echo 'Upgrading packages...';apt upgrade -y;a;tail -f /dev/null;"]
    environment:
      - DB_USER=admin
      - DB_PASS=verysecurepassword
      - DB_HOST=resspectdb
      - DB_PORT=5432
      - DB_NAME=resspectdb


    depends_on:
      - db
  db:
    container_name: resspectdb
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=verysecurepassword
      - POSTGRES_DB=resspectdb
    volumes:
      - ./resspectdb.sql:/docker-entrypoint-initdb.d/resspectdb.sql

volumes:
  db-data:
